"""create users table

Revision ID: ff0e5cbbd52d
Revises: 
Create Date: 2026-03-31 16:51:56.375726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0e5cbbd52d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=20), nullable=True),
    sa.Column('age_group', sa.Enum('under16', 'high_school', 'college', 'age_26_35', 'age_36_50', 'age_51_plus', name='age_group_enum'), nullable=False),
    sa.Column('max_free_sessions', sa.Integer(), nullable=False),
    sa.Column('used_free_sessions', sa.Integer(), nullable=False),
    sa.Column('api_key_registered', sa.Boolean(), nullable=False),
    sa.Column('english_level', sa.Enum('beginner', 'elementary', 'intermediate', 'upper_intermediate', name='english_level_enum'), nullable=True),
    sa.Column('primary_goal', sa.String(length=500), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('referred_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'deleted', name='user_status_enum'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
